// Etap 7 (SPEC-fleet-service.md §14) — read projections mirroring
// fleet-service's own fleet.vehicle.upserted/fleet.trailer.upserted
// events field-for-field (see Events/fleet.vehicle.upserted.mjs /
// fleet.trailer.upserted.mjs for the source of truth on what's carried).
// No deleted_at column: the upserted events don't fire on delete (that's
// its own fleet.vehicle.deleted/fleet.trailer.deleted topic), so a
// separate `is_deleted` flag set by that consumer is used instead.
exports.up = async function (knex) {
  await knex.raw(`
    CREATE TABLE fleet_vehicles (
      id                              uuid PRIMARY KEY,
      company_id                      uuid NOT NULL,
      kind                            text NOT NULL,
      status                          text NOT NULL,
      internal_code                   text,
      registration_number             text NOT NULL,
      registration_country            text NOT NULL,
      registration_certificate_number text,
      registration_holder_name        text,
      first_registration_date         date,
      current_registration_date       date,
      vin                             text NOT NULL,
      make                            text NOT NULL,
      type_variant_version             text,
      model                           text,
      type_approval_number            text,
      vehicle_category                text,
      manufacture_year                smallint,
      color                           text,
      operation_scope                 text NOT NULL,
      engine_number                   text,
      engine_capacity_cc              int,
      engine_power_kw                 int,
      fuel_type                       text,
      euro_class                      text,
      fuel_tank_l                     int,
      adblue_tank_l                   int,
      battery_capacity_kwh            numeric(7,1),
      max_permissible_mass_kg         int,
      permissible_mass_in_service_kg  int,
      gross_combination_mass_kg       int,
      kerb_mass_kg                    int,
      payload_kg                      int,
      max_braked_trailer_mass_kg      int,
      max_unbraked_trailer_mass_kg    int,
      max_axle_load_kg                int,
      axles                           smallint,
      axle_configuration              text,
      length_mm                       int,
      width_mm                        int,
      height_mm                       int,
      wheelbase_mm                    int,
      fifth_wheel_height_mm           int,
      seats                           smallint,
      sleeper_cab                     boolean,
      body_type                       text,
      cargo_length_mm                 int,
      cargo_width_mm                  int,
      cargo_height_mm                 int,
      cargo_volume_m3                 numeric(6,2),
      pallet_places                   smallint,
      tail_lift                       boolean,
      tail_lift_capacity_kg           int,
      crane                           boolean,
      adr_equipped                    boolean NOT NULL,
      adr_vehicle_type                text,
      tunnel_restriction_code         text,
      tachograph_type                 text,
      tachograph_make                 text,
      tachograph_serial               text,
      speed_limiter_kmh               smallint,
      telematics_provider             text,
      telematics_device_id            text,
      tyre_size_front                 text,
      tyre_size_rear                  text,
      ownership_type                  text NOT NULL,
      lessor_name                     text,
      lease_contract_number           text,
      lease_start_date                date,
      lease_end_date                  date,
      subcontractor_company_id        uuid,
      purchase_date                   date,
      in_service_date                 date,
      sale_date                       date,
      deregistration_date             date,
      odometer_km                     int,
      odometer_at                     timestamptz,
      engine_hours                    int,
      notes                           text,
      source                          text NOT NULL,
      version                         int NOT NULL,
      created_at                      timestamptz,
      updated_at                      timestamptz,
      is_deleted                      boolean NOT NULL DEFAULT false,
      synced_at                       timestamptz NOT NULL DEFAULT now()
    )
  `);
  await knex.raw(`CREATE INDEX fleet_vehicles_company_idx ON fleet_vehicles (company_id) WHERE NOT is_deleted`);

  await knex.raw(`
    CREATE TABLE fleet_trailers (
      id                              uuid PRIMARY KEY,
      company_id                      uuid NOT NULL,
      kind                            text NOT NULL,
      status                          text NOT NULL,
      internal_code                   text,
      registration_number             text NOT NULL,
      registration_country            text NOT NULL,
      registration_certificate_number text,
      registration_holder_name        text,
      first_registration_date         date,
      current_registration_date       date,
      vin                             text NOT NULL,
      make                            text NOT NULL,
      type_variant_version             text,
      model                           text,
      type_approval_number            text,
      vehicle_category                text,
      manufacture_year                smallint,
      color                           text,
      body_type                       text NOT NULL,
      body_variant                    text,
      sliding_roof                    boolean,
      coil_well                       boolean,
      side_boards                     boolean,
      xl_certified                    boolean,
      pallet_places                   smallint,
      internal_length_mm              int,
      internal_width_mm               int,
      internal_height_mm              int,
      cargo_volume_m3                 numeric(6,2),
      tail_lift                       boolean,
      tail_lift_capacity_kg           int,
      reefer_unit_make                text,
      reefer_unit_model               text,
      reefer_unit_serial              text,
      reefer_unit_hours               int,
      temp_min_c                      numeric(4,1),
      temp_max_c                      numeric(4,1),
      multi_temp                      boolean,
      compartments                    smallint,
      temperature_recorder            boolean,
      tank_capacity_l                 int,
      tank_compartments               smallint,
      tank_code                       text,
      tank_material                   text,
      food_grade                      boolean,
      max_permissible_mass_kg         int,
      permissible_mass_in_service_kg  int,
      kerb_mass_kg                    int,
      payload_kg                      int,
      max_axle_load_kg                int,
      kingpin_load_kg                 int,
      axles                           smallint,
      lift_axle                       boolean,
      steering_axle                   boolean,
      length_mm                       int,
      width_mm                        int,
      height_mm                       int,
      tyre_size                       text,
      adr_equipped                    boolean NOT NULL,
      adr_vehicle_type                text,
      tunnel_restriction_code         text,
      ownership_type                  text NOT NULL,
      lessor_name                     text,
      lease_contract_number           text,
      lease_start_date                date,
      lease_end_date                  date,
      subcontractor_company_id        uuid,
      purchase_date                   date,
      in_service_date                 date,
      sale_date                       date,
      deregistration_date             date,
      telematics_provider             text,
      telematics_device_id            text,
      notes                           text,
      source                          text NOT NULL,
      version                         int NOT NULL,
      created_at                      timestamptz,
      updated_at                      timestamptz,
      is_deleted                      boolean NOT NULL DEFAULT false,
      synced_at                       timestamptz NOT NULL DEFAULT now()
    )
  `);
  await knex.raw(`CREATE INDEX fleet_trailers_company_idx ON fleet_trailers (company_id) WHERE NOT is_deleted`);
};

exports.down = async function (knex) {
  await knex.schema.dropTableIfExists("fleet_trailers");
  return knex.schema.dropTableIfExists("fleet_vehicles");
};
