// Central registry of audit.action's `action` field values (spec rule
// 12: "namespaced string from a central registry, like the error
// codes"). One source of truth so a new action can't typo its way past
// review, and so a future consumer (Etap 9's nightly checksum, an audit
// UI) has a closed list to validate against. Add here first, before any
// service starts publishing a new one — <domain>.<what_happened>,
// snake_case, matching the shape every action already published.
export const AUDIT_ACTIONS = [
  "company_member.linked",
  "company_member.role_changed",
  "company_member.deleted",
  "company_member.deactivated_by_downgrade",
  "fleet_vehicle.created",
  "fleet_vehicle.updated",
  "fleet_vehicle.status_changed",
  "fleet_vehicle.deleted",
  "fleet_vehicle.restored",
  "fleet_vehicle.registration_changed",
  "fleet_trailer.created",
  "fleet_trailer.updated",
  "fleet_trailer.status_changed",
  "fleet_trailer.deleted",
  "fleet_trailer.restored",
  "fleet_trailer.registration_changed",
  "fleet_combination.attached",
  "fleet_combination.detached",
  "fleet_vehicle_driver.assigned",
  "fleet_vehicle_driver.unassigned",
  "fleet_vehicle_driver.set_primary",
  "fleet_driver_profile.updated",
  "fleet_driver_profile.number_revealed",
  "fleet_document.created",
  "fleet_document.updated",
  "fleet_document.renewed",
  "fleet_document.deleted",
  "fleet_document.restored",
  "fleet_document_file.attached",
  "fleet_document_file.detached",
  "fleet_attachment.added",
  "fleet_attachment.removed",
  "fleet_odometer.recorded",
  "fleet_odometer.corrected",
  "fleet_maintenance_plan.upserted",
  "fleet_maintenance_plan.deactivated",
  "fleet_maintenance_record.created",
  "fleet_maintenance_record.updated",
  "fleet_tyre.upserted",
  "fleet_tyre.mounted",
  "fleet_tyre.unmounted",
  "fleet_equipment.upserted",
  "fleet_equipment.deleted",
  "fleet_toll_device.upserted",
  "fleet_toll_device.assigned",
  "fleet_toll_device.status_changed",
  "fleet_tacho_download.recorded",
  "fleet_damage_report.created",
  "fleet_damage_report.updated",
  "fleet_damage_report.file_attached",
  "fleet_extraction.requested",
  "fleet_extraction.confirmed",
  "fleet_extraction.rejected",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
